### ISSUE TITLE
LESS incorrect style

### ISSUE THREAD

**Issue by montogeek** [equinusocio/material-theme#87]
Hi!

I found an issue with LESS code, a class with an uppercase word nested get a different color, check the V letter in `initialValue`, `currentValue` or `maxValue`.

This doesn't happen with other color schemes. 

![screen shot 2015-06-14 at 16 24 44](https://cloud.githubusercontent.com/assets/1002461/8150492/edfef180-12b1-11e5-8d2d-04fad96b78f7.png)

```less
.budget {
  padding: 30px;
  background-color: @main-color;

  &__values {
    width: 100%;
    position: relative;
    overflow: hidden;
    color: #FFFFFF;
    font-size: 1.2em;
    margin-bottom: 5px;

    &__initialValue {
      float: left;
    }

    &__currentValue {
      position: absolute;
      left: 0;
      transform: translate3d(-100%, 0, 0);
      transition: all 1s cubic-bezier(0, 0, 0.2, 1);
    }
    &__maxValue {
      float: right;
    }
  }

  &__progressBar {
    height: 15px;
    background-color: #AEDCAE;
    width: 100%;
    border-radius: 8px;

    &__progress {
      height: 100%;
      width: 0%;
      background-color: #FFFFFF;
      border-radius: 8px;
      transition: all 1s cubic-bezier(0, 0, 0.2, 1);
    }
  }
}
```
